apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: counter-service
  labels:
    app: counter-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
      - name: counter-service
        image: cirobessa/counter-service:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
